services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/actuator/health"] # Ajuste a porta se necessário
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s # Dá tempo para a aplicação iniciar
    networks:
     - quiz-network
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=quiz
    networks:
      - quiz-network
networks:
  quiz-network:
    driver: bridge